export const QUOTES_LOADING = "QUOTES_LOADING";
export const QUOTES_LOADED = "QUOTES_LOADED";
export const QUOTES_LOADING_FAILED = "QUOTES_LOADING_FAILED";

export const SAVED_QUOTES_LOADING = "SAVED_QUOTES_LOADING";
export const SAVED_QUOTES_LOADING_FAILED = "SAVED_QUOTES_LOADING_FAILED";
export const SAVE_QUOTES_LOADED = "SAVE_QUOTES_LOADED";

export const MEME_LOADING = "MEME_LOADING";
export const MEME_LOADED = "MEME_LOADED";
export const MEME_LOADING_FAILED = "MEME_LOADING_FAILED";
